name: Run Pytest on Commit (Windows)

on:
  push:
    branches:
      - main  # 监听 main 分支的提交

  # pull_request:
  #   branches:
  #     - main  # 监听 PR（Pull Request）到 main 分支

jobs:
  test:
    runs-on: windows-latest  # 运行环境改为 Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 拉取最新代码

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # 使用 Python 3.12

      - name: Install Dependencies
        run: |
          # python -m pip install --upgrade pip
          pip install pytest flask  # 只安装 pytest 和 flask

      - name: Run Pytest
        run: pytest ./test_main_api.py  # 运行 pytest 测试
